package DS4H.removedialog;

import DS4H.ImageFile;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionListener;
import java.text.MessageFormat;
import java.util.List;

public class RemoveImageDialog extends JDialog {
    private JPanel contentPane;
    private JButton btn_close;
    private JButton btn_delete;
    private JPanel pnl_buttons;
    private JScrollPane pnl_images_s;
    private List<ImageFile> imageFiles;

    public RemoveImageDialog(List<ImageFile> imageFiles) {
        $$$setupUI$$$();
        setContentPane(contentPane);
        this.setResizable(false);
        this.setTitle("Remove image");
        this.imageFiles = imageFiles;
        this.getContentPane().getInsets().set(20, 10, 20, 10);

        try {
            JPanel pnl_images = new JPanel();
            pnl_images.setLayout(new BoxLayout(pnl_images, BoxLayout.Y_AXIS));
            pnl_images.setAlignmentX(Component.LEFT_ALIGNMENT);
            pnl_images_s.setViewportView(pnl_images);
            pnl_images.getInsets().set(20, 10, 20, 10);

            for (int i = 0; i < imageFiles.size(); i++) {
                ImageFile imageFile = imageFiles.get(i);

                JPanel imageFilePanel = new JPanel();
                imageFilePanel.setLayout(new BoxLayout(imageFilePanel, BoxLayout.Y_AXIS));
                imageFilePanel.setAlignmentX(Component.LEFT_ALIGNMENT);


                JPanel filePanel = new JPanel();
                filePanel.setLayout(new BoxLayout(filePanel, BoxLayout.X_AXIS));
                filePanel.setAlignmentX(Component.LEFT_ALIGNMENT);//0.0
                JRadioButton rdb_select = new JRadioButton();
                rdb_select.setMargin(new Insets(0, 0, 0, 10));
                filePanel.add(rdb_select);
                JPanel pnl_fileDescription = new JPanel();
                pnl_fileDescription.setLayout(new BoxLayout(pnl_fileDescription, BoxLayout.Y_AXIS));
                JLabel lbl = new JLabel(MessageFormat.format("File {0}, {1} Images", i + 1, imageFile.getNImages(), imageFile.getNImages()));
                lbl.setHorizontalAlignment(SwingConstants.LEFT);
                pnl_fileDescription.add(lbl);
                JLabel lbl_filePath = new JLabel(MessageFormat.format("{0}", imageFile.getPathFile()));
                lbl_filePath.setFont(new Font(lbl_filePath.getFont().getName(), lbl_filePath.getFont().getStyle(), lbl_filePath.getFont().getSize() - 1));
                lbl_filePath.setForeground(Color.GRAY);
                pnl_fileDescription.add(lbl_filePath);
                filePanel.add(pnl_fileDescription);


                JPanel imagesPanel = new JPanel();
                imagesPanel.setLayout(new FlowLayout(FlowLayout.LEFT));
                imageFile.getThumbs().forEach(thumb -> {
                    ImageIcon icon = new ImageIcon(thumb);
                    imagesPanel.add(new JLabel(icon));
                });
            /*    imageFilePanel.add(filePanel);
                imageFilePanel.add(imagesPanel);
                pnl_images.add(imageFilePanel);*/
                imageFilePanel.add(leftJustify(filePanel));
                imageFilePanel.add(leftJustify(imagesPanel));

                pnl_images.add(topJustify(imageFilePanel

                ));
                imageFilePanel.getInsets().set(10, 10, 10, 10);
            }

            this.setMinimumSize(new Dimension(700, 600));
            this.setMaximumSize(new Dimension(700, 600));

            this.btn_close.addActionListener(event -> this.setVisible(false));
            this.pack();
            this.getInsets().set(20, 20, 20, 20);
        } catch (Exception e) {
            e.printStackTrace();

        }
    }

    private Component leftJustify(JPanel panel) {
        Box b = Box.createHorizontalBox();
        b.add(panel);
        b.add(Box.createHorizontalGlue());
        // (Note that you could throw a lot more components
        // and struts and glue in here.)
        return b;
    }

    private Component topJustify(JPanel panel) {
        Box b = Box.createVerticalBox();
        b.add(panel);
        b.add(Box.createVerticalBox());
        // (Note that you could throw a lot more components
        // and struts and glue in here.)
        return b;
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        contentPane = new JPanel();
        contentPane.setLayout(new BorderLayout(0, 0));
        pnl_buttons = new JPanel();
        pnl_buttons.setLayout(new FlowLayout(FlowLayout.RIGHT, 5, 5));
        contentPane.add(pnl_buttons, BorderLayout.SOUTH);
        btn_delete = new JButton();
        btn_delete.setText("Delete");
        pnl_buttons.add(btn_delete);
        btn_close = new JButton();
        btn_close.setText("Close");
        pnl_buttons.add(btn_close);
        pnl_images_s = new JScrollPane();
        pnl_images_s.setAlignmentX(0.0f);
        pnl_images_s.setAlignmentY(0.0f);
        contentPane.add(pnl_images_s, BorderLayout.CENTER);
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new BorderLayout(0, 0));
        pnl_images_s.setViewportView(panel1);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return contentPane;
    }

}
