package DS4H.removedialog;

import DS4H.ImageFile;

import javax.swing.*;
import java.awt.*;
import java.awt.print.Book;
import java.text.MessageFormat;
import java.util.List;

public class RemoveImageDialog extends JDialog {
    private JPanel contentPane;
    private JButton btn_close;
    private JButton btn_delete;
    private JPanel pnl_buttons;
    private JPanel pnl_images;

    public RemoveImageDialog(List<ImageFile> imageFiles) {
        $$$setupUI$$$();
        setContentPane(contentPane);
        this.setResizable(false);
        this.setTitle("Remove image");
/*
        for (int i = 0; i < imageFiles.size(); i++) {
            ImageFile imageFile = imageFiles.get(i);

            JPanel imageFilePanel = new JPanel();
            imageFilePanel.setLayout(new BorderLayout());

            JPanel filePanel = new JPanel();
            filePanel.setLayout(new BoxLayout(filePanel, BoxLayout.X_AXIS));
            JRadioButton rdb_select = new JRadioButton();
            rdb_select.setMargin(new Insets(0, 0, 0, 10));
            filePanel.add(rdb_select);
            JPanel pnl_fileDescription = new JPanel();
            pnl_fileDescription.setLayout(new BoxLayout(pnl_fileDescription, BoxLayout.Y_AXIS));
            pnl_fileDescription.add(new JLabel(MessageFormat.format("File {0}, {1} Images", i + 1, imageFile.getNImages(), imageFile.getNImages())));
            JLabel lbl_filePath = new JLabel(MessageFormat.format("{0}", imageFile.getPathFile()));
            lbl_filePath.setFont(new Font(lbl_filePath.getFont().getName(), lbl_filePath.getFont().getStyle(), lbl_filePath.getFont().getSize() - 1));
            lbl_filePath.setForeground(Color.GRAY);
            pnl_fileDescription.add(lbl_filePath);
            filePanel.add(pnl_fileDescription);

            JPanel imagesPanel = new JPanel();
            imagesPanel.setLayout(new BoxLayout(filePanel, BoxLayout.X_AXIS));
            imageFile.getThumbs();

            imageFilePanel.add(filePanel);
            pnl_images.add(imageFilePanel);
        }
*/
        DefaultListModel<ImageFile> model = new DefaultListModel<>();
        imageFiles.forEach(model::addElement);
        JList<ImageFile> lst_images = new JList<>(model);
        lst_images.setCellRenderer(new ImageFileRenderer());

        JScrollPane pane = new JScrollPane(lst_images);
        pnl_images.add(pane, BorderLayout.CENTER);

        this.setMinimumSize(new Dimension(600, 600));
        this.setMaximumSize(new Dimension(600, 600));
        this.setPreferredSize(new Dimension(600, 600));
        this.pack();
        this.getInsets().set(100, 100, 100, 100);
    }


    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        contentPane = new JPanel();
        contentPane.setLayout(new BorderLayout(0, 0));
        pnl_buttons = new JPanel();
        pnl_buttons.setLayout(new FlowLayout(FlowLayout.RIGHT, 5, 5));
        contentPane.add(pnl_buttons, BorderLayout.SOUTH);
        btn_delete = new JButton();
        btn_delete.setText("Delete");
        pnl_buttons.add(btn_delete);
        btn_close = new JButton();
        btn_close.setText("Close");
        pnl_buttons.add(btn_close);
        pnl_images = new JPanel();
        pnl_images.setLayout(new BorderLayout(5, 5));
        contentPane.add(pnl_images, BorderLayout.CENTER);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return contentPane;
    }

}
